<?php
namespace App\Tests\AbstractClass;

use App\Core\Context\Context;
use App\Kernel;
use App\Tests\Component\AssertExtension;
use Doctrine\Common\DataFixtures\ReferenceRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Bundle\FrameworkBundle\Client;

abstract class AbstractUnitTestCase extends WebTestCase
{
    use AssertExtension;

    /**
     * @var Client
     */
    protected static $client;

    /**
     * @var  ReferenceRepository
     */
    protected $_oReferenceRepository;

    protected function setUp()
    {
        Context::tearDown();
        parent::setUp();
    }
    
    protected function tearDown()
    {
        Context::tearDown();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass();
        self::setGeneralProperties();
    }

    protected static function setGeneralProperties()
    {
        self::$client = static::createClient();
    }
    
    /**
     * @return Container
     */
    public function getContainer() : Container
    {
        return self::$client->getContainer();
    }
    
    protected function getClient() : Client
    {
        return self::$client;
    }
}